# ============================================================
# 📈 Global Stock Intelligence Dashboard
# Author: Generated by Claude (Anthropic)
# Stack: Streamlit · Plotly · Pandas
# ============================================================

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import warnings
warnings.filterwarnings("ignore")

# ── PAGE CONFIG ──────────────────────────────────────────────
st.set_page_config(
    page_title="Stock Intelligence",
    page_icon="📈",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ── GLOBAL CSS ───────────────────────────────────────────────
st.markdown("""
<style>
/* ── Base & Fonts ── */
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap');

html, body, [class*="css"] {
    font-family: 'Inter', sans-serif;
}

/* Hide Streamlit chrome — keep header visible so sidebar toggle works */
#MainMenu, footer { visibility: hidden; }
header { visibility: visible; background: transparent !important; }
.block-container { padding-top: 1.5rem; padding-bottom: 2rem; }
.stDeployButton { display: none !important; }
/* Style the sidebar collapse/expand arrow */
[data-testid="collapsedControl"] { color: #a78bfa !important; }
button[kind="header"] { color: #a78bfa !important; }

/* ── Hero Banner ── */
.hero-banner {
    background: linear-gradient(135deg, #0f0c29, #302b63, #24243e);
    border-radius: 20px;
    padding: 2.5rem 3rem;
    margin-bottom: 1.5rem;
    position: relative;
    overflow: hidden;
    border: 1px solid rgba(255,255,255,0.08);
}
.hero-banner::before {
    content: '';
    position: absolute;
    top: -60px; right: -60px;
    width: 300px; height: 300px;
    background: radial-gradient(circle, rgba(99,102,241,0.25) 0%, transparent 70%);
    border-radius: 50%;
}
.hero-title {
    font-size: 2.4rem; font-weight: 800;
    background: linear-gradient(90deg, #a78bfa, #60a5fa, #34d399);
    -webkit-background-clip: text; -webkit-text-fill-color: transparent;
    margin: 0; line-height: 1.2;
}
.hero-subtitle {
    color: rgba(255,255,255,0.65); font-size: 1.05rem;
    font-weight: 400; margin-top: 0.4rem;
}

/* ── KPI Cards ── */
.kpi-grid { display: grid; grid-template-columns: repeat(4,1fr); gap: 1rem; margin-bottom: 1.5rem; }
.kpi-card {
    background: rgba(255,255,255,0.04);
    border: 1px solid rgba(255,255,255,0.1);
    border-radius: 16px;
    padding: 1.4rem 1.6rem;
    backdrop-filter: blur(10px);
    transition: all 0.25s ease;
    position: relative; overflow: hidden;
}
.kpi-card::after {
    content: ''; position: absolute;
    top: 0; left: 0; right: 0; height: 3px;
    border-radius: 16px 16px 0 0;
}
.kpi-card.purple::after { background: linear-gradient(90deg, #a78bfa, #7c3aed); }
.kpi-card.blue::after   { background: linear-gradient(90deg, #60a5fa, #2563eb); }
.kpi-card.green::after  { background: linear-gradient(90deg, #34d399, #059669); }
.kpi-card.orange::after { background: linear-gradient(90deg, #fb923c, #ea580c); }
.kpi-card:hover { transform: translateY(-3px); border-color: rgba(255,255,255,0.2); box-shadow: 0 12px 40px rgba(0,0,0,0.4); }
.kpi-label { color: rgba(255,255,255,0.5); font-size: 0.78rem; font-weight: 500; text-transform: uppercase; letter-spacing: 0.08em; }
.kpi-value { color: #ffffff; font-size: 2rem; font-weight: 800; margin: 0.3rem 0 0.1rem; }
.kpi-sub   { color: rgba(255,255,255,0.4); font-size: 0.78rem; }

/* ── Section Headers ── */
.section-header {
    font-size: 1.3rem; font-weight: 700; color: #e2e8f0;
    margin: 1.5rem 0 1rem;
    display: flex; align-items: center; gap: 0.5rem;
}
.section-header span { color: #a78bfa; }

/* ── Glass Cards ── */
.glass-card {
    background: rgba(255,255,255,0.04);
    border: 1px solid rgba(255,255,255,0.1);
    border-radius: 16px;
    padding: 1.5rem;
    backdrop-filter: blur(10px);
    margin-bottom: 1rem;
}

/* ── Stock Profile Card ── */
.stock-profile {
    background: linear-gradient(135deg, rgba(99,102,241,0.15), rgba(16,185,129,0.1));
    border: 1px solid rgba(99,102,241,0.3);
    border-radius: 20px; padding: 1.8rem 2rem; margin-bottom: 1.5rem;
}
.stock-name { font-size: 1.8rem; font-weight: 800; color: #fff; }
.stock-ticker { font-size: 0.9rem; color: #a78bfa; font-weight: 600; letter-spacing: 0.05em; }
.stock-country { font-size: 0.85rem; color: rgba(255,255,255,0.5); margin-top: 0.2rem; }

/* ── Metric Mini Cards ── */
.metric-row { display: grid; grid-template-columns: repeat(3, 1fr); gap: 0.8rem; margin-top: 1rem; }
.metric-card {
    background: rgba(0,0,0,0.25); border-radius: 12px;
    padding: 1rem; border: 1px solid rgba(255,255,255,0.07);
    transition: transform 0.2s;
}
.metric-card:hover { transform: translateY(-2px); }
.metric-label { font-size: 0.7rem; color: rgba(255,255,255,0.4); text-transform: uppercase; letter-spacing: 0.06em; }
.metric-val   { font-size: 1.25rem; font-weight: 700; color: #fff; margin-top: 0.2rem; }
.metric-val.green { color: #34d399; }
.metric-val.red   { color: #f87171; }
.metric-val.blue  { color: #60a5fa; }

/* ── Insight Cards ── */
.insight-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 1rem; }
.insight-card {
    background: rgba(255,255,255,0.03);
    border: 1px solid rgba(255,255,255,0.09);
    border-left: 3px solid;
    border-radius: 12px; padding: 1rem 1.2rem;
    transition: all 0.2s;
}
.insight-card:hover { background: rgba(255,255,255,0.06); transform: translateX(3px); }
.insight-title { font-size: 0.75rem; font-weight: 600; text-transform: uppercase; letter-spacing: 0.07em; margin-bottom: 0.4rem; }
.insight-text  { font-size: 0.9rem; color: rgba(255,255,255,0.75); line-height: 1.5; }

/* ── Skill Badges ── */
.badge-grid { display: flex; flex-wrap: wrap; gap: 0.7rem; }
.badge {
    background: rgba(99,102,241,0.15);
    border: 1px solid rgba(99,102,241,0.35);
    border-radius: 50px; padding: 0.45rem 1.1rem;
    font-size: 0.82rem; font-weight: 600; color: #a78bfa;
    transition: all 0.2s;
}
.badge:hover { background: rgba(99,102,241,0.3); transform: scale(1.04); }

/* ── AI Insight Box ── */
.ai-box {
    background: linear-gradient(135deg, rgba(16,185,129,0.1), rgba(99,102,241,0.15));
    border: 1px solid rgba(16,185,129,0.3);
    border-radius: 16px; padding: 1.5rem 2rem;
}
.ai-label { font-size: 0.7rem; font-weight: 700; color: #34d399; letter-spacing: 0.1em; text-transform: uppercase; }
.ai-value  { font-size: 1.1rem; font-weight: 600; color: #fff; margin-top: 0.2rem; }
.ai-desc   { font-size: 0.85rem; color: rgba(255,255,255,0.55); margin-top: 0.3rem; }

/* ── Data Quality ── */
.quality-ring { text-align: center; }
.quality-score { font-size: 3.5rem; font-weight: 900; background: linear-gradient(135deg,#34d399,#60a5fa); -webkit-background-clip:text; -webkit-text-fill-color:transparent; }
.quality-label { font-size: 0.85rem; color: rgba(255,255,255,0.5); }

/* ── Sidebar Styling ── */
[data-testid="stSidebar"] {
    background: linear-gradient(180deg, #0f0c29 0%, #1a1535 100%);
    border-right: 1px solid rgba(255,255,255,0.07);
}
[data-testid="stSidebar"] .stSelectbox label,
[data-testid="stSidebar"] .stMultiSelect label,
[data-testid="stSidebar"] p { color: rgba(255,255,255,0.75) !important; }
[data-testid="stSidebar"] h1, [data-testid="stSidebar"] h2 { color: #fff !important; }

/* ── Tabs ── */
.stTabs [data-baseweb="tab-list"] { gap: 0.5rem; background: transparent; }
.stTabs [data-baseweb="tab"] {
    background: rgba(255,255,255,0.04);
    border: 1px solid rgba(255,255,255,0.1);
    border-radius: 10px; color: rgba(255,255,255,0.6);
    font-weight: 500; padding: 0.5rem 1.2rem;
    transition: all 0.2s;
}
.stTabs [aria-selected="true"] {
    background: linear-gradient(135deg, rgba(99,102,241,0.3), rgba(60,130,245,0.2));
    border-color: rgba(99,102,241,0.5);
    color: #fff !important;
}

/* ── Scrollbar ── */
::-webkit-scrollbar { width: 6px; height: 6px; }
::-webkit-scrollbar-track { background: #0f0c29; }
::-webkit-scrollbar-thumb { background: rgba(99,102,241,0.5); border-radius: 10px; }

/* ── Responsive ── */
@media (max-width: 768px) {
    .kpi-grid { grid-template-columns: repeat(2, 1fr); }
    .metric-row { grid-template-columns: repeat(2, 1fr); }
    .insight-grid { grid-template-columns: 1fr; }
}

/* Background */
.stApp {
    background: linear-gradient(160deg, #0d0b1e 0%, #111827 100%);
}
</style>
""", unsafe_allow_html=True)

# ── PLOTLY THEME ─────────────────────────────────────────────
PLOTLY_THEME = dict(
    template="plotly_dark",
    paper_bgcolor="rgba(0,0,0,0)",
    plot_bgcolor="rgba(0,0,0,0)",
    font=dict(family="Inter", color="#e2e8f0"),
    margin=dict(l=10, r=10, t=40, b=10),
    colorway=["#a78bfa","#60a5fa","#34d399","#fb923c","#f472b6","#facc15","#2dd4bf","#e879f9"],
)

def apply_theme(fig, title="", height=380):
    fig.update_layout(**PLOTLY_THEME, title=dict(text=title, font=dict(size=14, color="#e2e8f0")), height=height)
    fig.update_xaxes(gridcolor="rgba(255,255,255,0.06)", showgrid=True, zeroline=False)
    fig.update_yaxes(gridcolor="rgba(255,255,255,0.06)", showgrid=True, zeroline=False)
    return fig

# ── DATA LOADING ─────────────────────────────────────────────
@st.cache_data(show_spinner=False)
def load_data():
    df = pd.read_csv("final_data.csv", parse_dates=["Date"])
    df = df.sort_values(["Stock_Name", "Date"]).reset_index(drop=True)
    df["Daily_Return"] = df.groupby("Stock_Name")["Close"].pct_change() * 100
    df["MA20"] = df.groupby("Stock_Name")["Close"].transform(lambda x: x.rolling(20, min_periods=1).mean())
    df["MA50"] = df.groupby("Stock_Name")["Close"].transform(lambda x: x.rolling(50, min_periods=1).mean())
    df["Volatility"] = df.groupby("Stock_Name")["Daily_Return"].transform(lambda x: x.rolling(20, min_periods=1).std())
    return df

@st.cache_data(show_spinner=False)
def compute_stock_stats(df):
    stats = df.groupby(["Stock_Name","Country"]).agg(
        Latest_Close=("Close","last"),
        Max_High=("High","max"),
        Min_Low=("Low","min"),
        Avg_Close=("Close","mean"),
        Total_Volume=("Volume","sum"),
        Std_Close=("Close","std"),
        Start_Close=("Close","first"),
    ).reset_index()
    stats["Total_Return_Pct"] = ((stats["Latest_Close"] - stats["Start_Close"]) / stats["Start_Close"]) * 100
    stats["Volatility_Score"] = (stats["Std_Close"] / stats["Avg_Close"]) * 100
    return stats

@st.cache_data(show_spinner=False)
def country_stats(df, stock_stats):
    cstats = stock_stats.groupby("Country").agg(
        Num_Stocks=("Stock_Name","count"),
        Avg_Return=("Total_Return_Pct","mean"),
        Avg_Volatility=("Volatility_Score","mean"),
        Total_Volume=("Total_Volume","sum"),
    ).reset_index()
    return cstats.sort_values("Total_Volume", ascending=False)

# ── LOAD ─────────────────────────────────────────────────────
with st.spinner("Loading market data…"):
    df = load_data()

stock_stats = compute_stock_stats(df)
cstats = country_stats(df, stock_stats)

all_stocks    = sorted(df["Stock_Name"].unique())
all_countries = sorted(df["Country"].unique())
date_min, date_max = df["Date"].min().date(), df["Date"].max().date()

# ── SIDEBAR ──────────────────────────────────────────────────
with st.sidebar:
    st.markdown("""
    <div style='text-align:center; padding: 1rem 0 0.5rem;'>
        <div style='font-size:2rem;'>📈</div>
        <div style='font-size:1.05rem; font-weight:700; color:#fff;'>StockVision Pro</div>
        <div style='font-size:0.75rem; color:rgba(255,255,255,0.4); margin-top:0.2rem;'>Global Market Analytics</div>
    </div>
    <hr style='border-color:rgba(255,255,255,0.08); margin:0.8rem 0;'/>
    """, unsafe_allow_html=True)

    st.markdown("**🌍 Country Filter**")
    sel_countries = st.multiselect("", options=all_countries, default=all_countries[:5], label_visibility="collapsed")

    st.markdown("**🔍 Stock Search**")
    search_q = st.text_input("", placeholder="Type stock name…", label_visibility="collapsed")

    available_stocks = sorted(
        df[df["Country"].isin(sel_countries)]["Stock_Name"].unique()
        if sel_countries else all_stocks
    )
    if search_q:
        available_stocks = [s for s in available_stocks if search_q.lower() in s.lower()]

    st.markdown("**📊 Select Stock**")
    sel_stock = st.selectbox("", options=available_stocks if available_stocks else all_stocks, label_visibility="collapsed")

    st.markdown("**📅 Date Range**")
    date_from = st.date_input("From", value=date_min, min_value=date_min, max_value=date_max, label_visibility="collapsed")
    date_to   = st.date_input("To",   value=date_max, min_value=date_min, max_value=date_max, label_visibility="collapsed")

    st.markdown("""
    <hr style='border-color:rgba(255,255,255,0.08); margin-top:1.5rem;'/>
    <div style='font-size:0.7rem; color:rgba(255,255,255,0.3); text-align:center; padding-bottom:1rem;'>
        Data spans Jan 2025 – May 2026<br/>300 stocks · 20 countries
    </div>
    """, unsafe_allow_html=True)

# ── FILTER DATA ──────────────────────────────────────────────
mask = (
    (df["Date"] >= pd.Timestamp(date_from)) &
    (df["Date"] <= pd.Timestamp(date_to))
)
if sel_countries:
    mask &= df["Country"].isin(sel_countries)
df_filtered = df[mask]

stock_df = df[(df["Stock_Name"] == sel_stock) & (df["Date"] >= pd.Timestamp(date_from)) & (df["Date"] <= pd.Timestamp(date_to))]
stock_info = stock_stats[stock_stats["Stock_Name"] == sel_stock].iloc[0] if not stock_stats[stock_stats["Stock_Name"] == sel_stock].empty else None

# ── HERO BANNER ──────────────────────────────────────────────
st.markdown("""
<div class="hero-banner">
    <div class="hero-title">📈 Stock Intelligence Dashboard</div>
    <div class="hero-subtitle">Interactive Financial Intelligence Platform · Real-Time Insights · 300+ Stocks · 20 Markets</div>
</div>
""", unsafe_allow_html=True)

# ── KPI CARDS ────────────────────────────────────────────────
total_stocks = df["Stock_Name"].nunique()
total_countries = df["Country"].nunique()
total_rows = len(df)
best_stock = stock_stats.loc[stock_stats["Total_Return_Pct"].idxmax(), "Stock_Name"]

st.markdown(f"""
<div class="kpi-grid">
    <div class="kpi-card purple">
        <div class="kpi-label">Total Stocks</div>
        <div class="kpi-value">{total_stocks}</div>
        <div class="kpi-sub">Across all markets</div>
    </div>
    <div class="kpi-card blue">
        <div class="kpi-label">Countries Covered</div>
        <div class="kpi-value">{total_countries}</div>
        <div class="kpi-sub">Global coverage</div>
    </div>
    <div class="kpi-card green">
        <div class="kpi-label">Total Data Points</div>
        <div class="kpi-value">{total_rows:,}</div>
        <div class="kpi-sub">OHLCV records</div>
    </div>
    <div class="kpi-card orange">
        <div class="kpi-label">Top Performer</div>
        <div class="kpi-value" style="font-size:1.3rem;">{best_stock}</div>
        <div class="kpi-sub">Highest total return</div>
    </div>
</div>
""", unsafe_allow_html=True)

# ── TABS ─────────────────────────────────────────────────────
tab1, tab2, tab3, tab4, tab5, tab6 = st.tabs([
    "📊 Stock Explorer",
    "🌍 Country Analytics",
    "📉 Market Overview",
    "🗃️ Data Quality",
    "💡 Market Insights",
    "🏆 Portfolio",
])

# ════════════════════════════════════════════════════════════
# TAB 1 – STOCK EXPLORER
# ════════════════════════════════════════════════════════════
with tab1:
    if stock_info is not None:
        ret_color = "#34d399" if stock_info["Total_Return_Pct"] >= 0 else "#f87171"
        ret_sign  = "+" if stock_info["Total_Return_Pct"] >= 0 else ""
        ticker    = df[df["Stock_Name"] == sel_stock]["Ticker"].iloc[0]

        st.markdown(f"""
        <div class="stock-profile">
            <div style="display:flex; justify-content:space-between; align-items:flex-start; flex-wrap:wrap; gap:1rem;">
                <div>
                    <div class="stock-name">{sel_stock}</div>
                    <div class="stock-ticker">NYSE: {ticker}</div>
                    <div class="stock-country">🌐 {stock_info['Country']}</div>
                </div>
                <div style="text-align:right;">
                    <div style="font-size:0.75rem; color:rgba(255,255,255,0.4); text-transform:uppercase; letter-spacing:0.07em;">Latest Close</div>
                    <div style="font-size:2.2rem; font-weight:900; color:#fff;">{stock_info['Latest_Close']:,.2f}</div>
                    <div style="font-size:1rem; font-weight:600; color:{ret_color};">{ret_sign}{stock_info['Total_Return_Pct']:.2f}% total return</div>
                </div>
            </div>
            <div class="metric-row">
                <div class="metric-card">
                    <div class="metric-label">All-Time High</div>
                    <div class="metric-val green">{stock_info['Max_High']:,.2f}</div>
                </div>
                <div class="metric-card">
                    <div class="metric-label">All-Time Low</div>
                    <div class="metric-val red">{stock_info['Min_Low']:,.2f}</div>
                </div>
                <div class="metric-card">
                    <div class="metric-label">Average Close</div>
                    <div class="metric-val blue">{stock_info['Avg_Close']:,.2f}</div>
                </div>
                <div class="metric-card">
                    <div class="metric-label">Total Volume</div>
                    <div class="metric-val">{stock_info['Total_Volume']/1e6:.1f}M</div>
                </div>
                <div class="metric-card">
                    <div class="metric-label">Volatility Score</div>
                    <div class="metric-val" style="color:#facc15;">{stock_info['Volatility_Score']:.1f}%</div>
                </div>
                <div class="metric-card">
                    <div class="metric-label">Data Points</div>
                    <div class="metric-val">{len(stock_df):,}</div>
                </div>
            </div>
        </div>
        """, unsafe_allow_html=True)

    if not stock_df.empty:
        c1, c2 = st.columns(2)

        with c1:
            # Price Trend + MAs
            fig = go.Figure()
            fig.add_trace(go.Scatter(x=stock_df["Date"], y=stock_df["Close"],
                mode="lines", name="Close",
                line=dict(color="#a78bfa", width=2),
                fill="tozeroy", fillcolor="rgba(167,139,250,0.08)"))
            fig.add_trace(go.Scatter(x=stock_df["Date"], y=stock_df["MA20"],
                mode="lines", name="MA 20", line=dict(color="#60a5fa", width=1.5, dash="dot")))
            fig.add_trace(go.Scatter(x=stock_df["Date"], y=stock_df["MA50"],
                mode="lines", name="MA 50", line=dict(color="#fb923c", width=1.5, dash="dash")))
            fig = apply_theme(fig, f"📈 {sel_stock} — Price & Moving Averages", 400)
            st.plotly_chart(fig, use_container_width=True)

        with c2:
            # Candlestick
            fig2 = go.Figure(data=[go.Candlestick(
                x=stock_df["Date"],
                open=stock_df["Open"], high=stock_df["High"],
                low=stock_df["Low"],  close=stock_df["Close"],
                increasing_line_color="#34d399", decreasing_line_color="#f87171",
                name="OHLC"
            )])
            fig2 = apply_theme(fig2, f"🕯️ {sel_stock} — Candlestick Chart", 400)
            st.plotly_chart(fig2, use_container_width=True)

        c3, c4 = st.columns(2)

        with c3:
            # Daily Returns
            returns_df = stock_df.dropna(subset=["Daily_Return"])
            fig3 = go.Figure()
            colors = ["#34d399" if r >= 0 else "#f87171" for r in returns_df["Daily_Return"]]
            fig3.add_trace(go.Bar(x=returns_df["Date"], y=returns_df["Daily_Return"],
                marker_color=colors, name="Daily Return %"))
            fig3 = apply_theme(fig3, f"📊 {sel_stock} — Daily Returns (%)", 350)
            st.plotly_chart(fig3, use_container_width=True)

        with c4:
            # Return Distribution
            fig4 = go.Figure()
            fig4.add_trace(go.Histogram(x=returns_df["Daily_Return"],
                nbinsx=50, name="Return Dist.",
                marker_color="#a78bfa", opacity=0.8))
            fig4.add_vline(x=0, line_dash="dash", line_color="rgba(255,255,255,0.3)")
            mean_r = returns_df["Daily_Return"].mean()
            fig4.add_vline(x=mean_r, line_dash="dot", line_color="#34d399",
                annotation_text=f"μ={mean_r:.2f}%", annotation_font_color="#34d399")
            fig4 = apply_theme(fig4, f"📉 {sel_stock} — Return Distribution", 350)
            st.plotly_chart(fig4, use_container_width=True)

        # Volume Chart
        fig5 = go.Figure()
        fig5.add_trace(go.Bar(x=stock_df["Date"], y=stock_df["Volume"],
            name="Volume", marker_color="rgba(96,165,250,0.6)"))
        fig5.add_trace(go.Scatter(x=stock_df["Date"],
            y=stock_df["Volume"].rolling(20, min_periods=1).mean(),
            mode="lines", name="20-Day MA Vol",
            line=dict(color="#facc15", width=2)))
        fig5 = apply_theme(fig5, f"📦 {sel_stock} — Volume Analysis", 320)
        st.plotly_chart(fig5, use_container_width=True)

# ════════════════════════════════════════════════════════════
# TAB 2 – COUNTRY ANALYTICS
# ════════════════════════════════════════════════════════════
with tab2:
    st.markdown('<div class="section-header">🌍 Country Performance Overview</div>', unsafe_allow_html=True)

    disp_cstats = cstats[cstats["Country"].isin(sel_countries)] if sel_countries else cstats

    c1, c2 = st.columns(2)

    with c1:
        fig = px.bar(disp_cstats.sort_values("Total_Volume"), x="Total_Volume", y="Country",
            orientation="h", color="Total_Volume", color_continuous_scale="Viridis",
            labels={"Total_Volume": "Total Volume Traded"})
        fig.update_layout(**PLOTLY_THEME, title="Total Trading Volume by Country",
            height=450, showlegend=False, coloraxis_showscale=False)
        fig.update_yaxes(tickfont=dict(size=11))
        st.plotly_chart(fig, use_container_width=True)

    with c2:
        fig2 = px.scatter(disp_cstats, x="Avg_Return", y="Avg_Volatility",
            size="Num_Stocks", color="Avg_Return",
            text="Country", color_continuous_scale="RdYlGn",
            labels={"Avg_Return": "Avg Return (%)", "Avg_Volatility": "Avg Volatility (%)"})
        fig2.update_traces(textposition="top center", textfont_size=10)
        fig2.update_layout(**PLOTLY_THEME, title="Risk vs. Return by Country",
            height=450, coloraxis_showscale=False)
        st.plotly_chart(fig2, use_container_width=True)

    c3, c4 = st.columns(2)

    with c3:
        top10_vol = disp_cstats.nlargest(10, "Total_Volume")
        fig3 = px.pie(top10_vol, names="Country", values="Total_Volume",
            hole=0.55, color_discrete_sequence=px.colors.qualitative.Vivid)
        fig3.update_layout(**PLOTLY_THEME, title="Volume Share — Top 10 Countries", height=380)
        fig3.update_traces(textinfo="percent+label", textfont_size=11)
        st.plotly_chart(fig3, use_container_width=True)

    with c4:
        fig4 = px.bar(disp_cstats.sort_values("Avg_Return", ascending=False),
            x="Country", y="Avg_Return",
            color="Avg_Return", color_continuous_scale="RdYlGn",
            labels={"Avg_Return": "Avg Return (%)"})
        fig4.update_layout(**PLOTLY_THEME, title="Average Stock Return by Country",
            height=380, coloraxis_showscale=False)
        st.plotly_chart(fig4, use_container_width=True)

    # Country stats table
    st.markdown('<div class="section-header">📋 Country Summary Table</div>', unsafe_allow_html=True)
    display_df = disp_cstats.copy()
    display_df["Avg_Return"] = display_df["Avg_Return"].map("{:.2f}%".format)
    display_df["Avg_Volatility"] = display_df["Avg_Volatility"].map("{:.2f}%".format)
    display_df["Total_Volume"] = display_df["Total_Volume"].map("{:,.0f}".format)
    display_df.columns = ["Country", "# Stocks", "Avg Return", "Avg Volatility", "Total Volume"]
    st.dataframe(display_df.reset_index(drop=True), use_container_width=True, height=350)

# ════════════════════════════════════════════════════════════
# TAB 3 – MARKET OVERVIEW
# ════════════════════════════════════════════════════════════
with tab3:
    st.markdown('<div class="section-header">📉 Broad Market Analysis</div>', unsafe_allow_html=True)

    # Top 15 by return
    top_performers = stock_stats.nlargest(15, "Total_Return_Pct")
    bot_performers = stock_stats.nsmallest(10, "Total_Return_Pct")

    c1, c2 = st.columns(2)

    with c1:
        fig = px.bar(top_performers.sort_values("Total_Return_Pct"),
            x="Total_Return_Pct", y="Stock_Name", orientation="h",
            color="Total_Return_Pct", color_continuous_scale="Greens",
            labels={"Total_Return_Pct": "Total Return (%)"})
        fig.update_layout(**PLOTLY_THEME, title="🏆 Top 15 Performers", height=480, coloraxis_showscale=False)
        st.plotly_chart(fig, use_container_width=True)

    with c2:
        fig2 = px.bar(bot_performers.sort_values("Total_Return_Pct", ascending=False),
            x="Total_Return_Pct", y="Stock_Name", orientation="h",
            color="Total_Return_Pct", color_continuous_scale="Reds_r",
            labels={"Total_Return_Pct": "Total Return (%)"})
        fig2.update_layout(**PLOTLY_THEME, title="📉 Bottom 10 Performers", height=480, coloraxis_showscale=False)
        st.plotly_chart(fig2, use_container_width=True)

    # Volatility vs Return scatter
    fig3 = px.scatter(stock_stats, x="Volatility_Score", y="Total_Return_Pct",
        color="Country", size="Total_Volume",
        hover_name="Stock_Name",
        labels={"Volatility_Score": "Volatility (%)", "Total_Return_Pct": "Total Return (%)"},
        size_max=35)
    fig3.update_layout(**PLOTLY_THEME, title="🎯 Risk vs. Return — All Stocks (bubble = volume)",
        height=480)
    st.plotly_chart(fig3, use_container_width=True)

    # Correlation heatmap (top 20 US stocks close prices)
    st.markdown('<div class="section-header">🔗 Correlation Heatmap — Top Stocks</div>', unsafe_allow_html=True)
    top20 = stock_stats.nlargest(20, "Total_Volume")["Stock_Name"].tolist()
    pivot = df[df["Stock_Name"].isin(top20)].pivot_table(index="Date", columns="Stock_Name", values="Close")
    corr = pivot.pct_change().corr()
    fig4 = px.imshow(corr, color_continuous_scale="RdBu_r", aspect="auto",
        labels=dict(color="Correlation"), zmin=-1, zmax=1)
    fig4.update_layout(**PLOTLY_THEME, title="Price Return Correlation — Top 20 by Volume",
        height=600)
    st.plotly_chart(fig4, use_container_width=True)

# ════════════════════════════════════════════════════════════
# TAB 4 – DATA QUALITY
# ════════════════════════════════════════════════════════════
with tab4:
    st.markdown('<div class="section-header">🗃️ Dataset Summary & Quality Score</div>', unsafe_allow_html=True)

    missing_count = df.isnull().sum().sum()
    dup_count     = df.duplicated().sum()
    completeness  = round(100 - (missing_count / df.size * 100), 1)
    uniqueness    = round(100 - (dup_count / len(df) * 100), 1)
    quality_score = round((completeness * 0.5 + uniqueness * 0.5), 1)

    c1, c2, c3 = st.columns([1,1,1])

    with c1:
        st.markdown(f"""
        <div class="glass-card" style="text-align:center;">
            <div class="quality-score">{quality_score}</div>
            <div style="font-size:1.1rem; font-weight:700; color:#34d399; margin-top:0.2rem;">Excellent Quality</div>
            <div class="quality-label">Dataset Quality Score / 100</div>
        </div>
        """, unsafe_allow_html=True)

    with c2:
        stats_rows = [
            ("Total Rows", f"{len(df):,}"),
            ("Total Columns", f"{len(df.columns)}"),
            ("Duplicate Rows", f"{dup_count}"),
            ("Date Range", f"{date_min} → {date_max}"),
        ]
        rows_html = "".join([f"<tr><td style='color:rgba(255,255,255,0.5);padding:0.4rem 0;'>{k}</td><td style='font-weight:600;color:#fff;'>{v}</td></tr>" for k,v in stats_rows])
        st.markdown(f"""
        <div class="glass-card">
            <div style="font-size:0.9rem; font-weight:600; color:#a78bfa; margin-bottom:0.8rem;">📋 Dataset Statistics</div>
            <table style="width:100%; border-collapse:collapse;">{rows_html}</table>
        </div>
        """, unsafe_allow_html=True)

    with c3:
        # Bar gauges
        metrics = {"Completeness": completeness, "Uniqueness": uniqueness, "Coverage": 100.0}
        fig = go.Figure()
        for name, val in metrics.items():
            color = "#34d399" if val >= 95 else "#facc15" if val >= 80 else "#f87171"
            fig.add_trace(go.Bar(x=[val], y=[name], orientation="h",
                marker_color=color, width=0.5, showlegend=False,
                text=f"{val:.1f}%", textposition="inside", insidetextanchor="middle"))
        fig.update_layout(**PLOTLY_THEME, title="Quality Dimensions", height=220,
            xaxis=dict(range=[0,100]), barmode="stack")
        st.plotly_chart(fig, use_container_width=True)

    st.markdown('<div class="section-header">🔍 Interactive Data Preview</div>', unsafe_allow_html=True)
    preview_stock = st.selectbox("Filter preview by stock:", ["All"] + all_stocks, key="preview_sel")
    preview_df = df if preview_stock == "All" else df[df["Stock_Name"] == preview_stock]
    st.dataframe(preview_df.tail(200).reset_index(drop=True), use_container_width=True, height=400)

    # Column type info
    with st.expander("📐 Schema & Column Types"):
        schema_df = pd.DataFrame({
            "Column": df.columns,
            "Type": [str(d) for d in df.dtypes],
            "Non-Null": [df[c].notna().sum() for c in df.columns],
            "Unique": [df[c].nunique() for c in df.columns],
        })
        st.dataframe(schema_df, use_container_width=True)

# ════════════════════════════════════════════════════════════
# TAB 5 – MARKET INSIGHTS
# ════════════════════════════════════════════════════════════
with tab5:
    st.markdown('<div class="section-header">💡 Dynamic Market Insights</div>', unsafe_allow_html=True)

    # Auto-generate 12 insights
    best_return_stock = stock_stats.loc[stock_stats["Total_Return_Pct"].idxmax()]
    worst_return_stock = stock_stats.loc[stock_stats["Total_Return_Pct"].idxmin()]
    lowest_vol_stock  = stock_stats.loc[stock_stats["Volatility_Score"].idxmin()]
    highest_vol_stock = stock_stats.loc[stock_stats["Volatility_Score"].idxmax()]
    top_country_vol   = cstats.iloc[0]
    best_country_ret  = cstats.loc[cstats["Avg_Return"].idxmax()]
    worst_country_ret = cstats.loc[cstats["Avg_Return"].idxmin()]
    usa_stocks        = len(stock_stats[stock_stats["Country"]=="USA"])
    overall_bull_bear = "Bullish" if stock_stats["Total_Return_Pct"].mean() > 0 else "Bearish"
    tech_stocks       = ["Apple","Microsoft","NVIDIA","Alphabet","Meta","Oracle","Netflix"]
    tech_avg_ret      = stock_stats[stock_stats["Stock_Name"].isin(tech_stocks)]["Total_Return_Pct"].mean()
    overall_avg_ret   = stock_stats["Total_Return_Pct"].mean()
    top_vol_stock     = stock_stats.loc[stock_stats["Total_Volume"].idxmax()]

    INSIGHT_COLORS = ["#a78bfa","#60a5fa","#34d399","#fb923c","#f472b6","#facc15","#2dd4bf","#e879f9","#a78bfa","#60a5fa","#34d399","#fb923c"]

    insights = [
        ("🏆 Top Performer", f"{best_return_stock['Stock_Name']} leads with an outstanding {best_return_stock['Total_Return_Pct']:.2f}% total return over the analysis period.", INSIGHT_COLORS[0]),
        ("📉 Worst Performer", f"{worst_return_stock['Stock_Name']} recorded the steepest decline at {worst_return_stock['Total_Return_Pct']:.2f}% total return.", INSIGHT_COLORS[1]),
        ("🧊 Most Stable Stock", f"{lowest_vol_stock['Stock_Name']} exhibits the lowest volatility score of {lowest_vol_stock['Volatility_Score']:.2f}%, ideal for risk-averse investors.", INSIGHT_COLORS[2]),
        ("🌋 Most Volatile Stock", f"{highest_vol_stock['Stock_Name']} carries the highest volatility score at {highest_vol_stock['Volatility_Score']:.2f}% — high risk, high reward.", INSIGHT_COLORS[3]),
        ("🌍 Trading Volume Giant", f"{top_country_vol['Country']} dominates trading volumes with {top_country_vol['Total_Volume']/1e9:.2f}B total shares traded.", INSIGHT_COLORS[4]),
        ("🚀 Best Country Returns", f"{best_country_ret['Country']} stocks generated the highest average return of {best_country_ret['Avg_Return']:.2f}%.", INSIGHT_COLORS[5]),
        ("⚠️ Weakest Market", f"{worst_country_ret['Country']} underperformed with an average return of {worst_country_ret['Avg_Return']:.2f}%.", INSIGHT_COLORS[6]),
        ("🇺🇸 US Dominance", f"USA contributes {usa_stocks} stocks to the dataset — the largest single-country representation.", INSIGHT_COLORS[7]),
        ("📈 Market Sentiment", f"Overall market sentiment is {overall_bull_bear}, with the average stock return at {overall_avg_ret:.2f}% across all covered equities.", INSIGHT_COLORS[8]),
        ("💻 Technology Sector", f"Tech stocks average {tech_avg_ret:.2f}% return, {'outperforming' if tech_avg_ret > overall_avg_ret else 'underperforming'} the broad market by {abs(tech_avg_ret-overall_avg_ret):.2f}%.", INSIGHT_COLORS[9]),
        ("📦 Volume Leader", f"{top_vol_stock['Stock_Name']} is the most actively traded stock with {top_vol_stock['Total_Volume']/1e9:.2f}B shares traded.", INSIGHT_COLORS[10]),
        ("🔢 Dataset Scale", f"With {total_rows:,} rows across {total_stocks} stocks and {total_countries} countries, this is an enterprise-grade multi-market dataset.", INSIGHT_COLORS[11]),
    ]

    st.markdown('<div class="insight-grid">', unsafe_allow_html=True)
    for title, text, color in insights:
        st.markdown(f"""
        <div class="insight-card" style="border-left-color:{color};">
            <div class="insight-title" style="color:{color};">{title}</div>
            <div class="insight-text">{text}</div>
        </div>
        """, unsafe_allow_html=True)
    st.markdown('</div>', unsafe_allow_html=True)

    # AI Style Summary Box
    st.markdown("<br>", unsafe_allow_html=True)
    st.markdown('<div class="section-header">🤖 AI-Style Market Intelligence</div>', unsafe_allow_html=True)
    risk_label = "High" if stock_stats["Volatility_Score"].mean() > 20 else "Moderate" if stock_stats["Volatility_Score"].mean() > 10 else "Low"

    st.markdown(f"""
    <div class="ai-box">
        <div style="display:grid; grid-template-columns:repeat(3,1fr); gap:1.5rem; flex-wrap:wrap;">
            <div>
                <div class="ai-label">Market Trend</div>
                <div class="ai-value">{'🟢 Bullish' if overall_avg_ret > 0 else '🔴 Bearish'}</div>
                <div class="ai-desc">Based on average stock returns across the full dataset period</div>
            </div>
            <div>
                <div class="ai-label">Highest Returning Stock</div>
                <div class="ai-value">🏆 {best_return_stock['Stock_Name']}</div>
                <div class="ai-desc">+{best_return_stock['Total_Return_Pct']:.2f}% total return over the analysis window</div>
            </div>
            <div>
                <div class="ai-label">Risk Category</div>
                <div class="ai-value">⚡ {risk_label} Risk</div>
                <div class="ai-desc">Average market volatility score: {stock_stats['Volatility_Score'].mean():.2f}%</div>
            </div>
            <div>
                <div class="ai-label">Dominant Country</div>
                <div class="ai-value">🌍 {top_country_vol['Country']}</div>
                <div class="ai-desc">Leads in total trading volume with {top_country_vol['Num_Stocks']} stocks</div>
            </div>
            <div>
                <div class="ai-label">Investment Observation</div>
                <div class="ai-value" style="font-size:0.95rem;">{'Tech stocks outperform the market.' if tech_avg_ret > overall_avg_ret else 'Tech stocks lag the market average.'}</div>
                <div class="ai-desc">Technology sector avg: {tech_avg_ret:.2f}% vs market avg: {overall_avg_ret:.2f}%</div>
            </div>
            <div>
                <div class="ai-label">Coverage Quality</div>
                <div class="ai-value">✅ {quality_score}/100</div>
                <div class="ai-desc">Excellent dataset completeness — zero missing values</div>
            </div>
        </div>
    </div>
    """, unsafe_allow_html=True)

# ════════════════════════════════════════════════════════════
# TAB 6 – PORTFOLIO / RECRUITER
# ════════════════════════════════════════════════════════════
with tab6:
    st.markdown('<div class="section-header">🏆 What This Dashboard Demonstrates</div>', unsafe_allow_html=True)
    st.markdown('<p style="color:rgba(255,255,255,0.55); margin-bottom:1.5rem;">This dashboard showcases a professional-grade financial analytics platform built with Python, Streamlit, and Plotly — reflecting skills across data engineering, analytics, and full-stack BI development.</p>', unsafe_allow_html=True)

    badges = [
        "✅ Data Cleaning & Wrangling",
        "✅ Exploratory Data Analysis",
        "✅ Business Intelligence",
        "✅ Data Visualization",
        "✅ Statistical Analysis",
        "✅ Financial Analytics",
        "✅ Streamlit Development",
        "✅ Plotly Visualization",
        "✅ Time-Series Analysis",
        "✅ Candlestick Charting",
        "✅ Volatility Modeling",
        "✅ Correlation Analysis",
        "✅ Moving Averages",
        "✅ KPI Dashboard Design",
        "✅ Responsive UI/UX",
        "✅ Performance Caching",
        "✅ Glassmorphism Design",
        "✅ Multi-Country Analytics",
        "✅ Dynamic Insights Engine",
        "✅ Production Code Quality",
    ]
    badge_html = " ".join([f'<span class="badge">{b}</span>' for b in badges])
    st.markdown(f'<div class="badge-grid">{badge_html}</div>', unsafe_allow_html=True)

    st.markdown("<br>", unsafe_allow_html=True)

    # Tech stack
    st.markdown('<div class="section-header">🛠️ Technology Stack</div>', unsafe_allow_html=True)
    stack = [
        ("🐍 Python 3", "Core Language", "#3b82f6"),
        ("📊 Streamlit", "Web App Framework", "#f43f5e"),
        ("📉 Plotly", "Interactive Charting", "#8b5cf6"),
        ("🐼 Pandas", "Data Manipulation", "#10b981"),
        ("🔢 NumPy", "Numerical Computing", "#f59e0b"),
        ("🎨 CSS3", "Custom Styling", "#06b6d4"),
    ]
    cols = st.columns(len(stack))
    for i, (icon_name, desc, color) in enumerate(stack):
        cols[i].markdown(f"""
        <div class="glass-card" style="text-align:center; border-top: 3px solid {color};">
            <div style="font-size:1.5rem;">{icon_name.split()[0]}</div>
            <div style="font-weight:700; color:#fff; margin-top:0.3rem; font-size:0.9rem;">{' '.join(icon_name.split()[1:])}</div>
            <div style="font-size:0.75rem; color:rgba(255,255,255,0.4);">{desc}</div>
        </div>
        """, unsafe_allow_html=True)

    # Dataset scale
    st.markdown("<br>", unsafe_allow_html=True)
    st.markdown('<div class="section-header">📊 Dataset Scope</div>', unsafe_allow_html=True)
    scope_cols = st.columns(4)
    scope_items = [
        ("300", "Global Stocks", "#a78bfa"),
        ("20", "Countries", "#60a5fa"),
        (f"{total_rows:,}", "Data Records", "#34d399"),
        ("9", "OHLCV Columns", "#fb923c"),
    ]
    for col, (val, label, color) in zip(scope_cols, scope_items):
        col.markdown(f"""
        <div class="kpi-card" style="text-align:center; border-top: 3px solid {color};">
            <div style="font-size:2.2rem; font-weight:900; color:{color};">{val}</div>
            <div style="font-size:0.82rem; color:rgba(255,255,255,0.5); margin-top:0.2rem;">{label}</div>
        </div>
        """, unsafe_allow_html=True)

    # Footer
    st.markdown("""
    <br>
    <div style="text-align:center; padding: 2rem; color:rgba(255,255,255,0.25); font-size:0.8rem; border-top: 1px solid rgba(255,255,255,0.06);">
        📈 Global Stock Intelligence Dashboard &nbsp;|&nbsp; Built with Streamlit & Plotly &nbsp;|&nbsp; Data: 2025–2026
    </div>
    """, unsafe_allow_html=True)
